### ISSUE TITLE
Create a docker-compose file for the application

### ISSUE THREAD

**Issue by kshitij10496** [kshitij10496/hercules#39]
It would be wonderful if we can get the application to run via a single command.
This would involve the use of `docker-compose` for managing multiple containers.
Ideally, we should have 2 services - one for the Postgres DB and another for the API.

**Comment by kshitij10496** [comment]
Here is a simple, non-functioning compose file I could come up with:

```yml
version: '3'
services:
  hercules_db:
    image: postgres
    ports:
      - "5432:5432"
    volumes: # Load the SQL dump to the container
      - ./hercules_backup_20181020.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_USER: postgres

  hercules_api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/github.com/kshitij10496/hercules
    depends_on:
      - db
    environment:
      - PORT=8080
      - HERCULES_DATABASE=#TODO: Update the connection string
```

@icyflame Could you help me with this? 😅
